name: Compose Docker project

on:
  push:
    branches:
      - main

jobs:
  docker-compose:
    runs-on: self-hosted
    environment: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Docker compose command
        env:
          SUI_WALLET_ADDRESS: ${{ secrets.SUI_WALLET_ADDRESS }}
          SUI_PRIVATE_KEY_CIPHER_TEXT: ${{ secrets.SUI_PRIVATE_KEY_CIPHER_TEXT }}
          SUI_PRIVATE_KEY_IV: ${{ secrets.SUI_PRIVATE_KEY_IV }}
          SUI_PRIVATE_KEY_KEY: ${{ secrets.SUI_PRIVATE_KEY_KEY }}
          SUI_PRIVATE_KEY: ${{ secrets.SUI_PRIVATE_KEY }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          REDIS_TTL: ${{ secrets.REDIS_TTL }}
          MONGODB_HOST: ${{ secrets.MONGODB_HOST }}
          MONGODB_PORT: ${{ secrets.MONGODB_PORT }}
          MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
          MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
          MONGODB_DB_NAME: ${{ secrets.MONGODB_DB_NAME }}
        run: docker compose -p cetus-clmm-bot up --build -d
